# Generated by Django 4.0.5 on 2022-06-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father', models.CharField(max_length=200)),
                ('foccu', models.CharField(max_length=200)),
                ('mother', models.CharField(max_length=200)),
                ('moccu', models.CharField(max_length=200)),
                ('child', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=200)),
                ('division', models.TextField()),
                ('desc', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
