# Generated by Django 4.0.5 on 2022-06-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission',
            old_name='father',
            new_name='Father',
        ),
        migrations.RenameField(
            model_name='admission',
            old_name='foccu',
            new_name='FatherOccupation',
        ),
        migrations.RenameField(
            model_name='admission',
            old_name='moccu',
            new_name='MotherOccupation',
        ),
        migrations.AlterField(
            model_name='admission',
            name='division',
            field=models.CharField(max_length=200),
        ),
    ]
