# Generated by Django 4.0.5 on 2022-06-23 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0002_rename_father_admission_father_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission',
            old_name='mother',
            new_name='Mother',
        ),
    ]
