# Generated by Django 4.0.5 on 2022-06-23 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0003_rename_mother_admission_mother'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission',
            old_name='address',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='admission',
            old_name='age',
            new_name='Age',
        ),
        migrations.RenameField(
            model_name='admission',
            old_name='child',
            new_name='Child',
        ),
        migrations.RenameField(
            model_name='admission',
            old_name='date',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='admission',
            old_name='desc',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='admission',
            old_name='division',
            new_name='Division',
        ),
        migrations.RenameField(
            model_name='admission',
            old_name='mobile',
            new_name='Mobile',
        ),
    ]
