# Generated by Django 4.0.5 on 2022-06-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0004_rename_address_admission_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Mobile', models.CharField(max_length=100)),
                ('Message', models.TextField()),
            ],
        ),
    ]
